trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main
      - dev

variables:
  TF_VERSION: '1.6.6'
  AWS_REGION: 'us-east-1'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - checkout: self

    - script: |
        echo "Installing AWS CLI v2..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

        echo "Installing session manager plugin (for AWS SSO)..."
        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
        sudo dpkg -i session-manager-plugin.deb
      displayName: "Install AWS CLI and session plugin"

    - script: |
        echo "Configuring AWS SSO login..."
        aws sso login --profile Terraform-admin
      displayName: "AWS SSO Login"

    - script: |
        terraform init -backend-config="bucket=myterraforms3bucketcloud" \
                       -backend-config="key=envs/dev/terraform.tfstate" \
                       -backend-config="region=$(AWS_REGION)" \
                       -backend-config="profile=Terraform-admin"
      displayName: 'Terraform Init'

    - script: terraform fmt -check
      displayName: 'Check Terraform Format'

    - script: terraform validate
      displayName: 'Terraform Validate'

    - script: terraform plan -out=tfplan
      displayName: 'Terraform Plan'
