- task: AWSShellScript@1
- task: S3Download@1
  inputs:
    awsCredentials: 'aws-service'
    regionName: 'eu-south-1'
    bucketName: 'myterraforms3bucketcloud'
    globExpressions: '**'
  inputs:
    awsCredentials: 'aws-service'
    regionName: 'eu-south-1'
    scriptType: 'inline'
    inlineScript: 'aws s3 ls'